import xml.dom.minidom

def prettify_xml(filename):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Parse and prettify
        dom = xml.dom.minidom.parseString(content)
        pretty_xml = dom.toprettyxml(indent="  ")
        
        # Remove extra empty lines often generated by minidom
        cleaned_xml = "\n".join([line for line in pretty_xml.splitlines() if line.strip()])
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(cleaned_xml)
        print(f"Successfully formatted {filename}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    prettify_xml("abc.mml")
